// Der Kartenstapel. Jeder Eintrag ist die Fortsetzung von „Ich hab noch nie …",
// klein geschrieben und ohne Punkt am Ende – die Oberfläche setzt den Anfang
// davor.
//
// Zwei getrennte Stapel, weil der Unterschied im Spiel wirklich einer ist:
// `harmlos` kann man an einem Familientisch vorlesen, `ab18` nicht. Gemischt
// wird erst im Server, je nach eingestelltem Modus.
//
// Alles selbst geschrieben. Aus keiner Spielanleitung und keiner App
// abgetippt – Regeln sind frei, fremde Kartentexte sind es nicht.

export const HARMLOS = [
  "im Unterricht oder in einer Besprechung eingeschlafen",
  "einen Knochen gebrochen",
  "mich selbst gegoogelt",
  "eine ganze Staffel an einem Tag durchgeschaut",
  "eine Nachricht an die völlig falsche Person geschickt",
  "so getan, als hätte ich ein Buch gelesen",
  "an einer Tür gezogen, auf der „drücken\" stand",
  "ein Geschenk weiterverschenkt",
  "eine Sprachnachricht dreimal neu aufgenommen",
  "beim Kochen den Rauchmelder ausgelöst",
  "mich krankgemeldet, obwohl ich fit war",
  "bei einem Brettspiel geschummelt",
  "jemanden gegrüßt, den ich gar nicht kannte",
  "behauptet, mein Akku sei leer gewesen",
  "beim Möbelaufbauen Schrauben übrig gehabt",
  "eine Zimmerpflanze verdursten lassen",
  "Geld gefunden und einfach behalten",
  "absichtlich nicht ans Telefon gegangen",
  "mich durch die alten Fotos von jemandem gescrollt",
  "beim Singen im Auto erwischt worden",
  "eine Prüfung ohne Lernen bestanden",
  "eine Prüfung trotz Lernen verhauen",
  "drei Tage dasselbe Shirt getragen",
  "mich verlaufen, obwohl ich ein Navi dabeihatte",
  "im Videocall stumm weitergeredet",
  "mich beim Friseur nicht getraut zu sagen, dass es mir nicht gefällt",
  "jemandem gesagt, das Essen schmeckt gut, obwohl es nicht stimmte",
  "den letzten Keks gegessen und es abgestritten",
  "schwarzgefahren",
  "eine Rolltreppe in der falschen Richtung genommen",
  "eine Nacht komplett durchgemacht",
  "im Bewerbungsgespräch ordentlich übertrieben",
  "auf einer Party eingeschlafen",
  "Karaoke gesungen",
  "einen Kaffee bestellt, dessen Namen ich nicht aussprechen konnte",
  "jemanden angerufen und aufgelegt, bevor es klingelte",
  "einen ganzen Tag im Bett verbracht",
  "behauptet, eine Mail nie bekommen zu haben",
  "auf einem Konzert geweint",
  "mich für ein Lied geschämt, das ich richtig mag",
  "beim Wandern behauptet, ich wüsste den Weg",
  "jemandem heimlich Pommes vom Teller geklaut",
  "im Supermarkt etwas probiert, bevor ich es bezahlt habe",
  "mich über eine Serie aufgeregt und trotzdem weitergeschaut",
  "so getan, als würde ich telefonieren, um jemandem auszuweichen",
  "meinen Schlüssel in der Wohnung eingeschlossen",
  "Wasser über eine Tastatur gekippt",
  "mich vor einem Gewitter verkrochen",
  "in einem See geschwommen, obwohl es verboten war",
  "mit dem Rad ohne Licht gefahren",
  "einen Zug verpasst, weil ich noch schnell etwas essen wollte",
  "mit vollem Mund geredet und jemanden dabei angespuckt",
  "einen Streamingdienst mit fremdem Passwort benutzt",
  "eine Kerze vergessen auszupusten",
  "jemandem die Handschrift nachgemacht",
  "mit Sonnenbrand nach Hause gekommen",
  "beim Sport so getan, als hätte ich mich verletzt",
  "einen Zahnarzttermin aus Angst verschoben",
  "mich in einem Escape Room komplett blamiert",
  "ein fremdes Tier gefüttert, obwohl ein Schild es verbot",
  "jemanden umarmt und gemerkt, dass es die falsche Person war",
  "drei Tage nicht aufs Handy geschaut",
  "beim Fußball mitgefiebert, obwohl mir das Ergebnis egal war",
  "einen Kuchen heimlich weggeworfen, den ich selbst gebacken habe",
  "die Spülmaschine mit voller Absicht falsch eingeräumt",
  "mich in einer fremden Stadt verfahren und nichts gesagt",
  "auf einer Rutsche gesteckt",
  "barfuß in etwas richtig Ekliges getreten",
  "auf einem Sofa geschlafen, weil ich zu faul zum Aufstehen war",
  "jemandem eine falsche Handynummer gegeben",
  "meinen eigenen Geburtstag vergessen zu erwähnen",
  "in der Öffentlichkeit laut mit mir selbst geredet",
  "eine Wette gewonnen, bei der ich keine Ahnung hatte",
  "in einem Restaurant gegessen, was mir nicht schmeckte, ohne etwas zu sagen",
  "beim Kartenspielen so lange verloren, bis ich beleidigt war",
  "einen Film empfohlen, den ich selbst nur halb gesehen habe",
  "meine Wohnung nur deshalb aufgeräumt, weil Besuch kam",
  "jemanden beim Gähnen angesteckt und mitgezählt",
  "aus Versehen jemandem ein altes Foto geliket",
  "einen Umzug versprochen und mich dann rausgeredet",
];

export const AB18 = [
  "mich an einen ganzen Abend nicht mehr erinnert",
  "betrunken eine Nachricht geschrieben, die ich am nächsten Tag bereut habe",
  "jemanden geküsst, dessen Namen ich nicht wusste",
  "in einem fremden Bett aufgewacht",
  "morgens in den Klamotten von gestern nach Hause gefahren",
  "einen One-Night-Stand gehabt",
  "auf einer Dating-App gelogen",
  "jemanden nach dem ersten Date einfach nicht mehr geantwortet",
  "bei einem Date Freunde angerufen, damit sie mich rausholen",
  "meinem Ex geschrieben, obwohl ich es besser wusste",
  "jemanden aus dem Freundeskreis geküsst",
  "mich in meine beste Freundin oder meinen besten Freund verliebt",
  "gleichzeitig mit zwei Leuten geschrieben, die beide dachten, sie wären die Einzigen",
  "eine Beziehung per Nachricht beendet",
  "jemanden angebaggert, der vergeben war",
  "einen Türsteher angelogen",
  "den Kater mit noch mehr Alkohol bekämpft",
  "mich wegen eines Katers krankgemeldet",
  "eine Runde für alle bezahlt und es am nächsten Tag bereut",
  "durchgetanzt und bin direkt zur Arbeit gefahren",
  "auf einer Firmenfeier deutlich zu viel erzählt",
  "mit einer Kollegin oder einem Kollegen geflirtet",
  "in einem Club auf einer Bühne getanzt",
  "betrunken gekocht",
  "mir betrunken selbst Essen für viel zu viel Geld bestellt",
  "mich übergeben und behauptet, es lag am Essen",
  "in einen Springbrunnen gestiegen",
  "auf einem Festival eine Woche nicht geduscht",
  "auf einer Party in der Badewanne geschlafen",
  "jemanden aus einem Club nach Hause bringen müssen",
  "nicht mehr gewusst, wie ich nach Hause gekommen bin",
  "einen Schnaps getrunken, den ich selbst zusammengemischt habe",
  "auf einer Hochzeit deutlich zu tief ins Glas geschaut",
  "gesagt „nur einen noch\" und bin um fünf heimgekommen",
  "mich betrunken ernsthaft nach einem Tattoo erkundigt",
  "in der Öffentlichkeit geknutscht, bis jemand etwas gesagt hat",
  "in einem Auto rumgemacht",
  "an einem Ort geknutscht, an dem man das eigentlich nicht sollte",
  "jemanden heimlich aus der Wohnung geschmuggelt",
  "jemanden geküsst, um eine Wette zu gewinnen",
  "nacktgebadet",
  "mich für ein Foto ausgezogen",
  "jemandem ein Foto geschickt, das ich lieber nicht geschickt hätte",
  "beim Sex lachen müssen",
  "beim Küssen den falschen Namen gesagt",
  "Sex gehabt, obwohl nebenan jemand war",
  "mit jemandem geschlafen und danach den Kontakt abgebrochen",
  "„ich liebe dich\" gesagt, weil ich betrunken war",
  "bei jemandem übernachtet, obwohl „nur reden\" abgemacht war",
  "einen Striptease hingelegt",
  "Sex an einem ziemlich ungewöhnlichen Ort gehabt",
  "meine Mitbewohner mit Absicht aus der Wohnung geekelt",
  "auf einer Party jemanden geküsst und danach nie wieder gesehen",
  "mich in jemanden verliebt, der auf der Party neben mir eingeschlafen ist",
  "mit dem Taxi heimgefahren, weil ich meine eigene Adresse vergessen hatte",
  "Unterwäsche verschenkt bekommen",
  "einem Date absichtlich einen falschen Beruf erzählt",
  "einen Abend lang so getan, als wäre ich Single",
];

/** Der Stapel zu einem Modus. `gemischt` legt beide zusammen. */
export function stapelFuer(modus) {
  if (modus === "harmlos") return HARMLOS.map((text) => ({ text, ab18: false }));
  if (modus === "ab18") return AB18.map((text) => ({ text, ab18: true }));
  return [
    ...HARMLOS.map((text) => ({ text, ab18: false })),
    ...AB18.map((text) => ({ text, ab18: true })),
  ];
}

export const MODI = ["harmlos", "gemischt", "ab18"];
